java -jar apktool.jar b ./AccountAndSyncSettings AccountAndSyncSettings1.apk
java -jar apktool.jar b ./ApplicationsProvider ApplicationsProvider1.apk
java -jar apktool.jar b ./Backup Backup1.apk
java -jar apktool.jar b ./Bluetooth Bluetooth1.apk
java -jar apktool.jar b ./Browser Browser1.apk
java -jar apktool.jar b ./Calculator Calculator1.apk
java -jar apktool.jar b ./Calendar Calendar1.apk
java -jar apktool.jar b ./CalendarProvider CalendarProvider1.apk
java -jar apktool.jar b ./CertInstaller CertInstaller1.apk
java -jar apktool.jar b ./CloudService CloudService1.apk
java -jar apktool.jar b ./Contacts Contacts1.apk
java -jar apktool.jar b ./ContactsProvider ContactsProvider1.apk
java -jar apktool.jar b ./DefaultContainerService DefaultContainerService1.apk
java -jar apktool.jar b ./DeskClock DeskClock1.apk
java -jar apktool.jar b ./DownloadProvider DownloadProvider1.apk
java -jar apktool.jar b ./DownloadProviderUi DownloadProviderUi1.apk
java -jar apktool.jar b ./DrmProvider DrmProvider1.apk
java -jar apktool.jar b ./DSPManager DSPManager1.apk
java -jar apktool.jar b ./Email Email1.apk
java -jar apktool.jar b ./FileExplorer FileExplorer1.apk
java -jar apktool.jar b ./Gallery Gallery1.apk
java -jar apktool.jar b ./HTMLViewer HTMLViewer1.apk
java -jar apktool.jar b ./Launcher2 Launcher21.apk
java -jar apktool.jar b ./LiveWallpapersPicker LiveWallpapersPicker1.apk
java -jar apktool.jar b ./MediaProvider MediaProvider1.apk
java -jar apktool.jar b ./MiuiCamera MiuiCamera1.apk
java -jar apktool.jar b ./MiuiMusic MiuiMusic1.apk
java -jar apktool.jar b ./Mms Mms1.apk
java -jar apktool.jar b ./Monitor Monitor1.apk
java -jar apktool.jar b ./MotoUsb MotoUsb1.apk
java -jar apktool.jar b ./MyNet MyNet1.apk
java -jar apktool.jar b ./Notes Notes1.apk
java -jar apktool.jar b ./PackageInstaller PackageInstaller1.apk
java -jar apktool.jar b ./Phone Phone1.apk
java -jar apktool.jar b ./Protips Protips1.apk
java -jar apktool.jar b ./Settings Settings1.apk
java -jar apktool.jar b ./SettingsProvider SettingsProvider1.apk
java -jar apktool.jar b ./SideKick SideKick1.apk
java -jar apktool.jar b ./SoundRecorder SoundRecorder1.apk
java -jar apktool.jar b ./Stk Stk1.apk
java -jar apktool.jar b ./Superuser Superuser1.apk
java -jar apktool.jar b ./SystemUI SystemUI1.apk
java -jar apktool.jar b ./TelephonyProvider TelephonyProvider1.apk
java -jar apktool.jar b ./ThemeManager ThemeManager1.apk
java -jar apktool.jar b ./Torch Torch1.apk
java -jar apktool.jar b ./VoiceDialer VoiceDialer1.apk
java -jar apktool.jar b ./VpnServices VpnServices1.apk