java -jar apktool.jar d AccountAndSyncSettings.apk ./AccountAndSyncSettings
java -jar apktool.jar d ApplicationsProvider.apk ./ApplicationsProvider
java -jar apktool.jar d Backup.apk ./Backup
java -jar apktool.jar d Bluetooth.apk ./Bluetooth
java -jar apktool.jar d Browser.apk ./Browser
java -jar apktool.jar d Calculator.apk ./Calculator
java -jar apktool.jar d Calendar.apk ./Calendar
java -jar apktool.jar d CalendarProvider.apk ./CalendarProvider
java -jar apktool.jar d CertInstaller.apk ./CertInstaller
java -jar apktool.jar d CloudService.apk ./CloudService
java -jar apktool.jar d Contacts.apk ./Contacts
java -jar apktool.jar d ContactsProvider.apk ./ContactsProvider
java -jar apktool.jar d DefaultContainerService.apk ./DefaultContainerService
java -jar apktool.jar d DeskClock.apk ./DeskClock
java -jar apktool.jar d DownloadProvider.apk ./DownloadProvider
java -jar apktool.jar d DownloadProviderUi.apk ./DownloadProviderUi
java -jar apktool.jar d DrmProvider.apk ./DrmProvider
java -jar apktool.jar d DSPManager.apk ./DSPManager
java -jar apktool.jar d Email.apk ./Email
java -jar apktool.jar d FileExplorer.apk ./FileExplorer
java -jar apktool.jar d Gallery.apk ./Gallery
java -jar apktool.jar d HTMLViewer.apk ./HTMLViewer
java -jar apktool.jar d Launcher2.apk ./Launcher2
java -jar apktool.jar d LiveWallpapersPicker.apk ./LiveWallpapersPicker
java -jar apktool.jar d MediaProvider.apk ./MediaProvider
java -jar apktool.jar d MiuiCamera.apk ./MiuiCamera
java -jar apktool.jar d MiuiMusic.apk ./MiuiMusic
java -jar apktool.jar d Mms.apk ./Mms
java -jar apktool.jar d Monitor.apk ./Monitor
java -jar apktool.jar d MotoUsb.apk ./MotoUsb
java -jar apktool.jar d MyNet.apk ./MyNet
java -jar apktool.jar d Notes.apk ./Notes
java -jar apktool.jar d PackageInstaller.apk ./PackageInstaller
java -jar apktool.jar d Phone.apk ./Phone
java -jar apktool.jar d Protips.apk ./Protips
java -jar apktool.jar d Settings.apk ./Settings
java -jar apktool.jar d SettingsProvider.apk ./SettingsProvider
java -jar apktool.jar d SideKick.apk ./SideKick
java -jar apktool.jar d SoundRecorder.apk ./SoundRecorder
java -jar apktool.jar d Stk.apk ./Stk
java -jar apktool.jar d Superuser.apk ./Superuser
java -jar apktool.jar d SystemUI.apk ./SystemUI
java -jar apktool.jar d TelephonyProvider.apk ./TelephonyProvider
java -jar apktool.jar d ThemeManager.apk ./ThemeManager
java -jar apktool.jar d Torch.apk ./Torch
java -jar apktool.jar d VoiceDialer.apk ./VoiceDialer
java -jar apktool.jar d VpnServices.apk ./VpnServices